template_path: template.yaml

region: ca-central-1

parameters:
  Role: !stack_output app/dev/base.yaml::FnRole
  TelegramBotToken: !aws ssm::get_parameter::'Name':'bot-token','WithDecryption':True::Parameter.Value::us-east-1
  TelegramChatId: !aws ssm::get_parameter::'Name':'/dlq-to-telegram/chat-id'::Parameter.Value::us-east-1
  DlqName: {{stack_group_config.dlq_name}}
